name: Scrape and Tweet Today Movie Release

on:
  schedule:
    - cron: '15 0,3 * * *'
  workflow_dispatch:

jobs:
  Scrape-and-Tweet:
    runs-on: macos-latest
    env:
      MONGO_CONNECTION_STRING: ${{ secrets.MONGO_CONNECTION_STRING }}
      MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}
      MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}
      TWITTER_USER_NAME: ${{ secrets.TWITTER_USER_NAME }} 
      TWITTER_APP_NAME: ${{ secrets.TWITTER_APP_NAME }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
    steps:
      - name: Start time
        run: echo "$(date) ** $(TZ=Asia/Jakarta date)"
      - uses: actions/checkout@v3 
      - uses: r-lib/actions/setup-r@v2
      - name: Install rvest package
        run: Rscript -e 'install.packages("rvest", dependencies = TRUE)'
      - name: Install mongolite package
        run: Rscript -e 'install.packages("mongolite", dependencies = TRUE)'
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", dependencies = TRUE)'
      - name: Install textutils package
        run: Rscript -e 'install.packages("textutils", dependencies = TRUE)'
      - name: Scrape new movies and insert into mongo
        run: Rscript scrape.R
      - name: Tweet today movie release
        run: Rscript tweet.R
